# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='os',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='browser',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
